### ISSUE TITLE
Update pool skill calculation

### ISSUE THREAD

**Issue by Gaikotsu2** [mapledyne/yaaz#11]
Using this appears to get the correct pool skill from gear, buffs, perm bonuses, and training bonuses.

```
matcher m = create_matcher("([0-9]+) at shooting",visit_url("questlog.php?which=3")); 
if (m.find()) pool_skill = m.group(1));
```

**Comment by mapledyne** [comment]
This requires a server call. Not a big deal if it improves things, but does it improve accuracy over the numbers we're already generating?

**Comment by Gaikotsu2** [comment]
It wouldn't need to be called on every cycle, could be called once during startup to set your baseline and then allow you to make more accurate choices for the various adventures.

**Comment by mapledyne** [comment]
I'd be curious how you'd structure this sort of check. It seems like the number would be stored (in a property?) and then manually recalculated based off that whenever something changed on the character, so we'd now have to track the semirare and training via the hustler, along with effects and equipment. Some of that can be discovered,  but it seems like a lot of manual calculation and tracking just to avoid using the built in and tracked-for-us properties and modifiers? 

I may easily be missing a benefit here (beyond just a mistrust of properties). Catch me in chat sometime and we can talk through this. Open to being convinced.

**Comment by mapledyne** [comment]
@Gaikotsu2 Any thoughts on this? What's the advantage of this over the current method?

**Comment by Gaikotsu2** [comment]
I'd be good with leaving it as is for now

**Comment by mapledyne** [comment]
OK. Going to close an we can readdress if it seems worth it in the future.
