### ISSUE TITLE
Add support for "lights out" quest line.

### ISSUE THREAD

**Issue by mapledyne** [mapledyne/yaaz#25]
Minimal ascension impact (though maybe auto-avoid if "aggressive optimize" is set) and maybe worth getting on the way.

**Comment by Gaikotsu2** [comment]
Should be 0 ascension impact since the adventures are free except for the final combat in each of the two lines.

**Comment by mapledyne** [comment]
I use the aggressiveoptimize option to allow a person to skip anything that takes even a single turn away from the ascension path - so things like fighting tentacles and such are skipped. This would seem to fit in that mold - skip the extra turn if you have that flag on, but without the flag, I think doing this path would be reasonable. That seems better than having a new flag just for this one questline due to the minimal (one turn) impact.

**Comment by mapledyne** [comment]
Initial  support added
