### ISSUE TITLE
Rename files to prevent name collisions

### ISSUE THREAD

**Issue by Gaikotsu2** [mapledyne/yaaz#30]
Need to rename files to something like "yz_*" to prevent file name collisions in Mafia. 

For instance, installing other scripts that have an "inventory.ash" anywhere in their hierarchy overrides and deletes "yaaz/util/base/inventory.ash".

**Comment by mapledyne** [comment]
Huh. I didn't know mafia wrecked files like that even in other directories. Weird. Just tested here and it does it as well. Good catch. Will take care of if you don't do it first.
