### ISSUE TITLE
Support pirate season

### ISSUE THREAD

**Issue by mikebryant** [mapledyne/yaaz#42]

**Comment by mikebryant** [comment]
Consider using something like `UberPvPOptimizer.ash`, so we don't need to maintain all the equipment/effect logic separately?

**Comment by mapledyne** [comment]
Using UberPVP would then require that script (or would skip PvP). There are these sorts of requirements in other places (no script = feature loss, like the time spinner far future), but is PvP "specialty" enough to be reasonable to require that other script? I don't mind passing it off to that script if it could be incorporated easily enough (I assume it could - I've not actually used it).
