### ISSUE TITLE
Nuns presume we're fighting the war as a fratboy

### ISSUE THREAD

**Issue by mapledyne** [mapledyne/yaaz#5]
Nun support needs help all around - we should calculate and make a decision on if we should try the nuns trick (if +meat is high enough)

**Comment by Gaikotsu2** [comment]
Will also want to see if it's possible to do the Nun Trick at all. If the character doesn't have the ability to copy a combat, it won't work.

**Comment by mapledyne** [comment]
I also want to add in a check for "can we get +meat% enough to be worth it?"

**Comment by mapledyne** [comment]
It doesn't do any auto-calculations to know to do the nuns, or trick, but it does ether if asked (yz_war_nuns, zy_war_nuns_trick)
