### ISSUE TITLE
Got stuck looping on the catburgling

### ISSUE THREAD

**Issue by mikebryant** [mapledyne/yaaz#58]
Somehow after all the friars stuff I only had 2 hot wings, which was unusual.
The script doesn't notice this case, and I ended up looping round the catburgle adventure 32 times :(

Working on a patch

**Comment by mapledyne** [comment]
Your contributions have been awesome - would it be helpful on your end to be bumped up to contributor instead of having to go through the PR route each time?

**Comment by mikebryant** [comment]
I'm happy to help maintain, triage issues, and review PRs, so yes, that would be helpful.

In my workplace we're big fans of getting people to review code, so I'm very conditioned at the moment to always have someone else merge things, so that side of things doesn't bother me. I don't mind waiting for someone else to be free to review and test, I think the four eyes principle helps.
(Though tbh I'm working on systems that underpin thousands of robots, so it's a wee bit more high stakes than kol :p)

So up to you really, if you'd like me to just merge things I can do. I'll probably leave PRs open for a while anyway though, just in case someone spots something important.

**Comment by mapledyne** [comment]
We have much better code processes at my work here, too. With yaaz I had about a few month of ad-hoc development with no extra eyes over any of it. I'd be very happy to set up some processes and even code standards to keep things consistent, though with only two active coders at this point it may not be worth it. For future refactors I'll feature branch them so you can look things over before I make changes on that scale now if you're willing. My email is michael@mapledyne.com if you want to chat off-git, too.

**Comment by mikebryant** [comment]
Mhm, it's often not worth it at small scale, especially for small projects.
I'm happy to review any PRs, feel free to ping me :)
