### ISSUE TITLE
Support License to Adventure

### ISSUE THREAD

**Issue by mikebryant** [mapledyne/yaaz#79]
- [x] Allow for no familiars
- [x] Don't go on the pandemonium quest - you can get a steel margarita, but not drink it
- [x] Cope with going on the daily quest? (Needs more info on what the optimal strategy for this might be)
- [x] Don't try and drink anything that's not shaken in the right glass
- [x] `inebriety_limit()` is currently wrong - I took skills to increase max drunkenness. Wait for kolmafia to fix upstream?
- [x] Don't sell martinis
- [x] Don't extrude browser cookies, since they're useless
- [x] Try and get a tuxedo shirt?
- [x] Make sure we get keys from the deck
- [x] Use each of the 3 bond combat items once a day if we have them (can lid/firecracker/spider's web)
- [x] Stick a key in `Which Door?` if we have a spare one, otherwise do the meat choice
- [x] `set_property("choiceAdventure1258", 2);` - to get the martini
- [x] Buy skills!
- [x] Use can of Minions-Be-Gone
- [x] Obtain can of Minions-Be-Gone from briefcase
- [x] Use Targeted Plague Vector if available
- [x] Don't get sacramento wine, as it can't be drunk
- [x] Maybe use time-spinner to get monsters that drop can/firecracker/spiders?
- [x] Don't get a drink from the far future, since we can't drink it
- [x] Use the partial bridge thing
- [x] Use victor's spoils

**Comment by mapledyne** [comment]
Excited for this. Ending an HCO loop soon and can dive into the path.

**Comment by mikebryant** [comment]
I am currently running the daily quest manually, then using yaaz for the rest

**Comment by mikebryant** [comment]
Currently having issues completing quests. kolmafia isn't updating the status on visiting the council, presumably because the text has changed.
Visiting the quest log/completed quests does work though

**Comment by mikebryant** [comment]
I think kolmafia's been updated with the right quest text now :)

**Comment by mikebryant** [comment]
Waiting for kolmafia to add quest text support for the daily quest
